### PR TITLE
Login notifications

### LINKED ISSUE #69: Give appropriate error messages
Give appropriate error messages as below - 
- ~~notify "network disconnected" on the "Scan QR code Screen" where the app defaults to when there is no network connectivity as currently it is going to the "Scan QR Code Screen" which may confuse people as being logged out.~~ See #70.
- When the app is not able to authenticate with the Management Portal, It just creates a toast saying that `Cannot reach the server. Please try again with internet connection` but instead the android logs show that its an authorization issue due to expired refresh token. Look at the logs below - 
```
03-23 11:01:03.885 28186-28229/? E/pRMT:ManagementPortalS*: Failed to get access token
                                                            java.io.IOException: Failed to make request; response {"error":"invalid_token","error_description":"Invalid refresh token (expired): eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJzb3VyY2VzIjpbImNmOGYwMzFjLTAzMmItNGU0MC05NTJiLTVjZGU3ZjNkMGJlOSIsImVkMWRiNzJmLWVkMDQtNGY5ZC05M2U3LTRmNjE2ZmIzYzZlNCIsIjA4ZGI1MjY1LTdkYmYtNGE3ZC05NjkyLTk0MzBlOGZmOTVkNiIsIjViMTk2ZGRjLTc5MDItNGMzMi1hZmFmLWNiOGJhZWMzZmYyMyJdLCJ1c2VyX25hbWUiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJyb2xlcyI6WyJSYWRhci10ZXN0IDpST0xFX1BBUlRJQ0lQQU5UIl0sImlzcyI6Ik1hbmFnZW1lbnRQb3J0YWwiLCJhdXRob3JpdGllcyI6WyJST0xFX1BBUlRJQ0lQQU5UIl0sImNsaWVudF9pZCI6InBSTVQiLCJhdWQiOlsicmVzX2dhdGV3YXkiLCJyZXNfTWFuYWdlbWVudFBvcnRhbCJdLCJncmFudF90eXBlIjpudWxsLCJzY29wZSI6WyJNRUFTVVJFTUVOVC5DUkVBVEUiLCJTVUJKRUNULlVQREFURSIsIlNVQkpFQ1QuUkVBRCIsIlBST0pFQ1QuUkVBRCIsIlNPVVJDRVRZUEUuUkVBRCIsIlNPVVJDRS5SRUFEIiwiU09VUkNFREFUQS5SRUFEIiwiVVNFUi5SRUFEIiwiUk9MRS5SRUFEIl0sImF0aSI6IjcxYjYwZTNmLWUxMDgtNDQ0NC05YzkyLThhZGFhMGUwMmFiMCIsImV4cCI6MTUyMTU0NzIyNSwiaWF0IjoxNTIxNTQ1MzI4LCJqdGkiOiJjMmQ1YzJiYy0zNjdlLTRhZTYtOGFhNC02ZmZkNTAyNmM2MDUifQ.gd1pa-T26yuvs4-nYq8tn8kWDCf7cMM2ccmWZKVkGEqrPF7ft3VKT3uNTVPHuAXYpYf8v2lvQtM-EJtSm2qu6fhQmi-jhPAJpC2qV2ZWcX_BaUse_VwlcQngkFILMWnpDsP2RtjVsVy8g6EWKM4T8BNzPjeRoLQ4zzRT9ZYXJNMSu35rMaWvG6GL7B7upCvTuhlsJ3n8sYmXHJLfb3Xj6vhOyEc6oj5mFiGsMzMqmp4TCwSCzWTEgwxwIrmuMBoIDMiPW3OiO8Tj-o3lwXFZbiNsdMDjIJHqQX_nTr0ekAl-i2K08MxLZKDN-QFnF1AE_7iW_Z-MgMDiHBArouUqaiY_EyvgA75OgH9bYroNWfsLtySk0jq7SoGH6pliYybDbJdN9C4Y7EfoefjvKBMyA8BGIW7FraXCFqx-a47Z3Q1pmOm1sdoWIKQTnvkk7uXTdyrxPBN6vKbBC_X3KrQXvE2dnzlG666Io3wnOcs1582se4n6IPKitaLYugGFlhQ7Wwoagd7nmfLz6I5xB3K-_rhrKJPGOWKftipyJbiEd7JiypoadpaUNN4pWSjJNBQZoKrmyIdnIpRIrPm6ulzB7IfGstLB7neNwx8JH3OHumKs8wuxx4cvKNQjs2Z7PC_-6RnsGH4UHQ21kI8T5k6Y0vsGOBHdjSWB1Q4YXJftp5A"}
                                                                at org.radarcns.android.util.ResponseHandler.handle(ResponseHandler.java:18)
                                                                at org.radarcns.android.auth.portal.ManagementPortalClient.refreshToken(ManagementPortalClient.java:162)
                                                                at org.radarcns.android.auth.portal.ManagementPortalService.refreshToken(ManagementPortalService.java:151)
                                                                at org.radarcns.android.auth.portal.ManagementPortalService.onHandleIntent(ManagementPortalService.java:99)
                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
03-23 11:01:03.885 28186-28186/? E/pRMT:RadarLoginActivity: Failed to log in with org.radarcns.android.auth.portal.ManagementPortalLoginManager@f67b38e
                                                            java.io.IOException: Cannot reach management portal
                                                                at org.radarcns.android.auth.portal.ManagementPortalLoginManager$1.onReceiveResult(ManagementPortalLoginManager.java:46)
                                                                at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
03-23 11:01:03.885 28186-28229/? E/pRMT:ManagementPortalS*: Failed to interact with ManagementPortal with AppAuthState{projectId='Radar-test ', 
                                                            userId='b7e5a48c-c16d-4b11-845b-b2f2626b4e75', 
                                                            token='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJzb3VyY2VzIjpbImNmOGYwMzFjLTAzMmItNGU0MC05NTJiLTVjZGU3ZjNkMGJlOSIsImVkMWRiNzJmLWVkMDQtNGY5ZC05M2U3LTRmNjE2ZmIzYzZlNCIsIjA4ZGI1MjY1LTdkYmYtNGE3ZC05NjkyLTk0MzBlOGZmOTVkNiIsIjViMTk2ZGRjLTc5MDItNGMzMi1hZmFmLWNiOGJhZWMzZmYyMyJdLCJ1c2VyX25hbWUiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJyb2xlcyI6WyJSYWRhci10ZXN0IDpST0xFX1BBUlRJQ0lQQU5UIl0sImlzcyI6Ik1hbmFnZW1lbnRQb3J0YWwiLCJhdXRob3JpdGllcyI6WyJST0xFX1BBUlRJQ0lQQU5UIl0sImNsaWVudF9pZCI6InBSTVQiLCJhdWQiOlsicmVzX2dhdGV3YXkiLCJyZXNfTWFuYWdlbWVudFBvcnRhbCJdLCJncmFudF90eXBlIjpudWxsLCJzY29wZSI6WyJNRUFTVVJFTUVOVC5DUkVBVEUiLCJTVUJKRUNULlVQREFURSIsIlNVQkpFQ1QuUkVBRCIsIlBST0pFQ1QuUkVBRCIsIlNPVVJDRVRZUEUuUkVBRCIsIlNPVVJDRS5SRUFEIiwiU09VUkNFREFUQS5SRUFEIiwiVVNFUi5SRUFEIiwiUk9MRS5SRUFEIl0sImV4cCI6MTUyMTU4ODUyNiwiaWF0IjoxNTIxNTQ1MzI4LCJqdGkiOiI3MWI2MGUzZi1lMTA4LTQ0NDQtOWM5Mi04YWRhYTBlMDJhYjAifQ.UXkiMu-z7Nk1G7KSDzWg7y7BDkdVw6MMjZsFZfhidaiU3KIYGm63YvYFG3NkkVWdKrBHSYJ6oNbStmD1IM8AEnLqRfHgyXlq6Y8XHWFSdsYOKbc8VQES2mxbSAq1cIkcDn2jbAaEM9onvSLPVLirdfx_DzE17_Yy9g0py_bViDKfrq_t3bf9JwXxwIHR-1jsfLjIH2ZGRSAadCRb5RhW5cjJySY9c99F2-7GhefeG927MlLoGAfBxH-c4ua4NKLl_vw_DhQjelaQGyhdks81YzLgAigKfiQs1-dw4QLhfwyusWiZlLZTE-5Am9tu_JNjzejwtXlAVYno1tRawwKvvyNrXqzEUkQsX4ebu4oxg2f-UqVuaDqqwIbez3p2IU9ynGkB1O1wXHw2KFCNlo3Dz-GSGH4Ub0XNLr3cH2FJSC8lHJhQXw8k3eFWwptxnu75oYwmi48PZFmAlfh83lh_4_k3zX0naCnzd5DFQoNv0mLzlnjgUSqIJUkak7zBsnkiTWq4MfMD1NvC4vhpq7W6XaZKQMEI7wBXKvjRV7lOkHjNPWuhxHkFkQZklF-T9Jy1Liv0vxWaYxaMq_HybsfoBx9ZiVQWL0GGoQMtzr1GUypaE-OUpNkQpGIBE5KrMQN7eJoBDrBKTrA0QoNoHxP6v5c6kjWelEIEMPfv9YAthYg', 
                                                            tokenType=1, 
                                                            expiration=0, 
                                                            lastUpdate=0, 
                                                            properties={org.radarcns.android.auth.portal.ManagementPortalClient.sources=[AppSource{sourceTypeId='1011', sourceTypeProducer='RADAR', sourceTypeModel='pRMT', sourceTypeCatalogVersion='v1', dynamicRegistration=true, sourceId='ed1db72f-ed04-4f9d-93e7-4f616fb3c6e4', sourceName='pRMT-ed1db72f', expectedSourceName='null', attributes={}'}, AppSource{sourceTypeId='1008', sourceTypeProducer='App', sourceTypeModel='THINC-IT', sourceTypeCatalogVersion='v1', dynamicRegistration=true, sourceId='a774cda1-2a54-40c2-9d42-9cde241c02f2', sourceName='THINC-IT-a774cda1', expectedSourceName='null', attributes={}'}, AppSource{sourceTypeId='1007', sourceTypeProducer='App', sourceTypeModel='aRMT-App', sourceTypeCatalogVersion='v1', dynamicRegistration=true, sourceId='08db5265-7dbf-4a7d-9692-9430e8ff95d6', sourceName='aRMT-App-08db5265', expectedSourceName='null', attributes={}'}, AppSource{sourceTypeId='1003', sourceTypeProducer='ANDROID', sourceTypeModel='PHONE', sourceTypeCatalogVersion='v1', dynamicRegistration=true, sourceId='cf8f031c-032b-4e40-952b-5cde7f3d0be9', sourceName='PHONE-cf8f031c', expectedSourceName='null', attributes={}'}, AppSource{sourceTypeId='1001', sourceTypeProducer='EMPATICA', sourceTypeModel='E4', sourceTypeCatalogVersion='v1', dynamicRegistration=true, sourceId='null', sourceName='null', expectedSourceName='null', attributes={}'}], org.radarcns.android.auth.portal.ManagementPortalClient.refreshToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJzb3VyY2VzIjpbImNmOGYwMzFjLTAzMmItNGU0MC05NTJiLTVjZGU3ZjNkMGJlOSIsImVkMWRiNzJmLWVkMDQtNGY5ZC05M2U3LTRmNjE2ZmIzYzZlNCIsIjA4ZGI1MjY1LTdkYmYtNGE3ZC05NjkyLTk0MzBlOGZmOTVkNiIsIjViMTk2ZGRjLTc5MDItNGMzMi1hZmFmLWNiOGJhZWMzZmYyMyJdLCJ1c2VyX25hbWUiOiJiN2U1YTQ4Yy1jMTZkLTRiMTEtODQ1Yi1iMmYyNjI2YjRlNzUiLCJyb2xlcyI6WyJSYWRhci10ZXN0IDpST0xFX1BBUlRJQ0lQQU5UIl0sImlzcyI6Ik1hbmFnZW1lbnRQb3J0YWwiLCJhdXRob3JpdGllcyI6WyJST0xFX1BBUlRJQ0lQQU5UIl0sImNsaWVudF9pZCI6InBSTVQiLCJhdWQiOlsicmVzX2dhdGV3YXkiLCJyZXNfTWFuYWdlbWVudFBvcnRhbCJdLCJncmFudF90eXBlIjpudWxsLCJzY29wZSI6WyJNRUFTVVJFTUVOVC5DUkVBVEUiLCJTVUJKRUNULlVQREFURSIsIlNVQkpFQ1QuUkVBRCIsIlBST0pFQ1QuUkVBRCIsIlNPVVJDRVRZUEUuUkVBRCIsIlNPVVJDRS5SRUFEIiwiU09VUkNFREFUQS5SRU


```

### PR DESCRIPTION
**Pull request by MaximMoinat**
Fixes #69
* More granular login fail messages
* When internet connection unavailable, disable scan button and show a warning text

### CODE REVIEW

File: app/src/main/java/org/radarcns/detail/RadarLoginActivity.java [hunk 1]
```diff
@@ -80,12 +110,14 @@ protected void onResume() {
         }
         canLogin = true;
         registerReceiver(configBroadcastReceiver, new IntentFilter(RADAR_CONFIGURATION_CHANGED));
+        registerReceiver(networkStateReceiver, new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
```
Comment (blootsvoets) [inline app/src/main/java/org/radarcns/detail/RadarLoginActivity.java]: Should probably query the network state here directly, if the network state doesn't change while on the page. See for example https://github.com/RADAR-base/radar-commons-android/blob/dc229411c230236bf37f338302193b7381f4f3a5/src/main/java/org/radarcns/android/util/NetworkConnectedReceiver.java#L43. In fact, you could use the NetworkConnectedReceiver here instead of the custom broadcast listener.

Comment (blootsvoets) [reply app/src/main/java/org/radarcns/detail/RadarLoginActivity.java]: e.g.

```java
onCreate() {
    this.networkReceiver = new NetworkConnectedReceiver(this, this);
}
onStart() {
    this.networkReciever.register();
}
onStop() {
    this.networkReceiver.unregister();
}
onNetworkConnectionChanged(boolean isConnected, boolean isWifiOrEthernet) {
    if (isConnected) {
       scanButton.setEnabled(true);
       messageBox.setText("");
    } else {
       scanButton.setEnabled(false);
       messageBox.setText(R.string.no_connection);
    }
}
```

Comment (MaximMoinat) [reply app/src/main/java/org/radarcns/detail/RadarLoginActivity.java]: Implemented! Thanks for the suggestion.
